package com.pista.spark.sql.metrics

import com.pista.spark.sql.metrics.collector.TaskAggregator
import com.pista.spark.sql.metrics.model._
import com.pista.spark.sql.metrics.writer.{DropPolicy, JsonLineWriter, MetricsQueue}
import org.apache.spark.internal.Logging
import org.apache.spark.sql.SparkSession
import org.scalatest.{BeforeAndAfterAll, BeforeAndAfterEach}
import org.scalatest.funsuite.AnyFunSuite

import java.nio.file.{Files, Paths}

/**
 */
class MetricsSuite extends AnyFunSuite with BeforeAndAfterEach with BeforeAndAfterAll with Logging {

  var spark: SparkSession = _
  val outputDir = "./metrics_output"

  override def beforeAll(): Unit =
    spark = SparkSession.builder()
      .appName("MetricsSuite")
      .master("local[2]")
      .config("spark.sql.shuffle.partitions", "2")
      .getOrCreate()

  override def afterAll(): Unit = {
    if (spark != null)
      spark.stop()

    // Clean the metrics_output directory generated by test generation exactly.
    val dir = new java.io.File(outputDir)
    if (dir.exists()) {
      def deleteRecursively(file: java.io.File): Unit = {
        if (file.isDirectory)
          file.listFiles().foreach(deleteRecursively)
        file.delete()
      }
      deleteRecursively(dir)
    }
  }

  // ==================== JsonLineWriter Test ====================

  test("JsonLineWriter should correctly write to a JSON Lines file") {

    val outputDir = "./metrics_output"
    val queue = new MetricsQueue[Metrics](100, DropPolicy.DropOldest)

    // create writer
    val writer = new JsonLineWriter(outputDir, queue, batchSize = 10, flushIntervalMs = 100)
    writer.start()

    // Persist some metrics
    queue.offer(JobMetrics(
      appId = "test-app",
      appName = "TestApp",
      jobId = 1,
      jobGroup = "sql-1",
      status = "SUCCEEDED",
      startTime = 1000L,
      endTime = 2000L,
      durationMs = 1000L,
      numStages = 2,
      numTasks = 10,
      collectTimestamp = Metrics.formatTime(System.currentTimeMillis())
    ))

    queue.offer(StageMetrics(
      appId = "test-app",
      stageId = 1,
      stageAttemptId = 0,
      jobId = 1,
      status = "COMPLETED",
      startTime = 1000L,
      endTime = 2000L,
      durationMs = 1000L,
      numTasks = 10,
      inputBytes = 1024L,
      inputRecords = 100L,
      outputBytes = 512L,
      outputRecords = 50L,
      shuffleReadBytes = 256L,
      shuffleWriteBytes = 128L,
      executorRunTime = 900L,
      executorCpuTime = 800000000L,
      jvmGcTime = 50L,
      collectTimestamp = Metrics.formatTime(System.currentTimeMillis())
    ))

    queue.offer(SQLMetrics(
      appId = "test-app",
      executionId = 1L,
      sqlText = "SELECT * FROM test_table WHERE id > 100",
      status = "SUCCESS",
      errorMessage = "",
      startTime = 1000L,
      endTime = 2000L,
      durationMs = 1000L,
      collectTimestamp = Metrics.formatTime(System.currentTimeMillis())
    ))

    queue.offer(TaskAggMetrics(
      appId = "test-app",
      stageId = 1,
      stageAttemptId = 0,
      taskCount = 10,
      durationMin = 100L,
      durationMax = 1000L,
      durationAvg = 550L,
      durationP50 = 500L,
      durationP95 = 900L,
      durationP99 = 1000L,
      skewRatio = 2.0,
      collectTimestamp = Metrics.formatTime(System.currentTimeMillis())
    ))

    // Await write completion
    Thread.sleep(500)

    // Stop writer (flushes remaining data)
    writer.stop()

    // Verify file exists
    val jobFile = Paths.get(outputDir, "job_metrics.jsonl")
    val stageFile = Paths.get(outputDir, "stage_metrics.jsonl")
    val sqlFile = Paths.get(outputDir, "sql_metrics.jsonl")
    val taskAggFile = Paths.get(outputDir, "task_agg_metrics.jsonl")

    assert(Files.exists(jobFile), "job_metrics.jsonl should exist")
    assert(Files.exists(stageFile), "stage_metrics.jsonl should exist")
    assert(Files.exists(sqlFile), "sql_metrics.jsonl should exist")
    assert(Files.exists(taskAggFile), "task_agg_metrics.jsonl should exist")

    // Validate file contents
    val jobContent = new String(Files.readAllBytes(jobFile))
    assert(jobContent.contains("\"metricType\":\"job\""))
    assert(jobContent.contains("\"appId\":\"test-app\""))

    val stageContent = new String(Files.readAllBytes(stageFile))
    assert(stageContent.contains("\"metricType\":\"stage\""))

    val sqlContent = new String(Files.readAllBytes(sqlFile))
    assert(sqlContent.contains("\"metricType\":\"sql\""))
    assert(sqlContent.contains("SELECT * FROM test_table"))

    val taskAggContent = new String(Files.readAllBytes(taskAggFile))
    assert(taskAggContent.contains("\"metricType\":\"task_agg\""))
    assert(taskAggContent.contains("\"skewRatio\":2.0"))

    // Print statistics
    val stats = writer.stats
    logInfo(s"Writing statistics: writeCount=${stats.writeCount}, errorCount=${stats.errorCount}")
    assert(stats.writeCount == 4, s"should write 4 rows, actual written ${stats.writeCount}")
    assert(stats.errorCount == 0, "There should be no errors.")
  }

  // ==================== MetricsQueue testing ====================

  test("MetricsQueue should correctly enqueue and dequeue") {
    val queue = new MetricsQueue[String](10, DropPolicy.DropOldest)

    assert(queue.offer("a"))
    assert(queue.offer("b"))
    assert(queue.offer("c"))
    assert(queue.size == 3)

    val drained = queue.drain(2)
    assert(drained == Seq("a", "b"))
    assert(queue.size == 1)
  }

  test("MetricsQueue is full should discard the oldest entries by the DropOldest strategy") {
    val queue = new MetricsQueue[Int](3, DropPolicy.DropOldest)

    queue.offer(1)
    queue.offer(2)
    queue.offer(3)
    assert(queue.size == 3)

    // Queue full, should overwrite the oldest (1)
    queue.offer(4)
    assert(queue.size == 3)
    assert(queue.droppedCount == 1)

    val drained = queue.drain(10)
    assert(drained == Seq(2, 3, 4))
  }

  test("MetricsQueue is full should discard the newest entries by the DropNewest strategy") {
    val queue = new MetricsQueue[Int](3, DropPolicy.DropNewest)

    queue.offer(1)
    queue.offer(2)
    queue.offer(3)

    // Queue full, should overwrite the current (4)
    val result = queue.offer(4)
    assert(!result)
    assert(queue.droppedCount == 1)

    val drained = queue.drain(10)
    assert(drained == Seq(1, 2, 3))
  }

  // ==================== TaskAggregator Test ====================

  test("TaskAggregator should correctly aggregate task metrics Task metrics have been aggregated correctly by the Task Aggregator.") {
    val aggregator = new TaskAggregator()

    // record the execution duration of 10 tasks 10 tasks Task the execution time
    val durations = Seq(100L, 200L, 300L, 400L, 500L, 600L, 700L, 800L, 900L, 1000L)
    durations.foreach(d => aggregator.record(1, 0, d))

    val result = aggregator.aggregateAndClear(1, 0, "app-123")
    assert(result.isDefined)

    val metrics = result.get
    assert(metrics.appId == "app-123")
    assert(metrics.stageId == 1)
    assert(metrics.stageAttemptId == 0)
    assert(metrics.taskCount == 10)
    assert(metrics.durationMin == 100L)
    assert(metrics.durationMax == 1000L)
    assert(metrics.durationAvg == 550L)
    // percentile calculation: index = (size - 1) * p
    // P50: index = 9 * 0.50 = 4, sorted(4) = 500
    assert(metrics.durationP50 == 500L)
    // P95: index = 9 * 0.95 = 8, sorted(8) = 900
    assert(metrics.durationP95 == 900L)
    // P99: index = 9 * 0.99 = 8, sorted(8) = 900
    assert(metrics.durationP99 == 900L)
    assert(metrics.skewRatio == 2.0) // 1000 / 500
  }

  test("TaskAggregator Aggregates and should clear data") {
    val aggregator = new TaskAggregator()

    aggregator.record(1, 0, 100L)
    aggregator.record(1, 0, 200L)

    val first = aggregator.aggregateAndClear(1, 0, "app-123")
    assert(first.isDefined)
    assert(first.get.taskCount == 2)

    // re-aggregation should return null None
    val second = aggregator.aggregateAndClear(1, 0, "app-123")
    assert(second.isEmpty)
  }

  test("TaskAggregator should support concurrent records across multiple stages Stage concurrent records") {
    val aggregator = new TaskAggregator()

    // Stage 1
    aggregator.record(1, 0, 100L)
    aggregator.record(1, 0, 200L)

    // Stage 2
    aggregator.record(2, 0, 300L)
    aggregator.record(2, 0, 400L)

    assert(aggregator.trackedStageCount == 2)

    val stage1 = aggregator.aggregateAndClear(1, 0, "app-123")
    assert(stage1.isDefined)
    assert(stage1.get.taskCount == 2)
    assert(stage1.get.durationAvg == 150L)

    val stage2 = aggregator.aggregateAndClear(2, 0, "app-123")
    assert(stage2.isDefined)
    assert(stage2.get.taskCount == 2)
    assert(stage2.get.durationAvg == 350L)
  }

  // ==================== Metrics MODEL TESTING ====================

  test("JobMetrics should serialize correctly to JSON") {
    val metrics = JobMetrics(
      appId = "app-123",
      appName = "TestApp",
      jobId = 1,
      jobGroup = "sql-1",
      status = "SUCCEEDED",
      startTime = 1000L,
      endTime = 2000L,
      durationMs = 1000L,
      numStages = 2,
      numTasks = 10,
      collectTimestamp = Metrics.formatTime(3000L)
    )

    val json = Metrics.toJson(metrics)
    assert(json.contains("\"metricType\":\"job\""))
    assert(json.contains("\"appId\":\"app-123\""))
    assert(json.contains("\"jobId\":1"))
    assert(json.contains("\"status\":\"SUCCEEDED\""))
  }

  test("StageMetrics Should Serialize Correctly to JSON") {
    val metrics = StageMetrics(
      appId = "app-123",
      stageId = 1,
      stageAttemptId = 0,
      jobId = 1,
      status = "COMPLETED",
      startTime = 1000L,
      endTime = 2000L,
      durationMs = 1000L,
      numTasks = 10,
      inputBytes = 1024L,
      inputRecords = 100L,
      outputBytes = 512L,
      outputRecords = 50L,
      shuffleReadBytes = 256L,
      shuffleWriteBytes = 128L,
      executorRunTime = 900L,
      executorCpuTime = 800000000L,
      jvmGcTime = 50L,
      collectTimestamp = Metrics.formatTime(3000L)
    )

    val json = Metrics.toJson(metrics)
    assert(json.contains("\"metricType\":\"stage\""))
    assert(json.contains("\"stageId\":1"))
    assert(json.contains("\"shuffleReadBytes\":256"))
  }

// test("SQLMetrics Should Serialize Correctly to JSON") {
//    val metrics = SQLMetrics(
//      appId = "app-123",
//      executionId = 1L,
//      sqlHash = "abc123",
//      sqlText = "SELECT * FROM test",
//      description = "SELECT * FROM test",
//      physicalPlan = "Scan test",
//      startTime = 1000L,
//      endTime = 2000L,
//      durationMs = 1000L,
//      collectTimestamp = Metrics.formatTime(3000L)
//    )
//
//    val json = Metrics.toJson(metrics)
//    assert(json.contains("\"metricType\":\"sql\""))
//    assert(json.contains("\"executionId\":1"))
//    assert(json.contains("\"sqlHash\":\"abc123\""))
//  }

  test("TaskAggMetrics should serialize correctly to JSON") {
    val metrics = TaskAggMetrics(
      appId = "app-123",
      stageId = 1,
      stageAttemptId = 0,
      taskCount = 10,
      durationMin = 100L,
      durationMax = 1000L,
      durationAvg = 550L,
      durationP50 = 500L,
      durationP95 = 900L,
      durationP99 = 1000L,
      skewRatio = 2.0,
      collectTimestamp = Metrics.formatTime(3000L)
    )

    val json = Metrics.toJson(metrics)
    assert(json.contains("\"metricType\":\"task_agg\""))
    assert(json.contains("\"skewRatio\":2.0"))
  }

  test("DataQualityMetrics Output sqlIndex on SELECT path and omit sourceType") {
    val metrics = DataQualityMetrics(
      appId = "app-123",
      executionId = 1L,
      tableName = "orders",
      sqlIndex = Some("sql_1"),
      totalRecords = 10L,
      collectTimestamp = Metrics.formatTime(3000L)
    )

    val json = Metrics.toJson(metrics)
    assert(json.contains("\"metricType\":\"data_quality\""))
    assert(json.contains("\"sqlIndex\":\"sql_1\""))
    assert(!json.contains("\"sourceType\""))
  }

  // ==================== TaskAggregator Skew Detection Test ====================

  test("TaskAggregator should correctly detect data skew (skewed)") {
    val aggregator = new TaskAggregator()

    // simulation 10 task Taskwhere 1 one is significantly slower (skewed)
    val durations = Seq(100L, 100L, 100L, 100L, 100L, 100L, 100L, 100L, 100L, 1000L)
    durations.foreach(d => aggregator.record(1, 0, d))

    val result = aggregator.aggregateAndClear(1, 0, "app-123")
    assert(result.isDefined)

    val metrics = result.get
    assert(metrics.skewRatio == 10.0) // 1000 / 100
    assert(metrics.skewRatio > 2.0, "Should detect data skew")
  }

  test("TaskAggregator should correctly detect data skew (no skew)") {
    val aggregator = new TaskAggregator()

    // simulation 10 tasks Taskuniform execution time across tasks
    val durations = Seq(100L, 110L, 105L, 95L, 100L, 105L, 100L, 95L, 100L, 100L)
    durations.foreach(d => aggregator.record(1, 0, d))

    val result = aggregator.aggregateAndClear(1, 0, "app-123")
    assert(result.isDefined)

    val metrics = result.get
    assert(metrics.skewRatio < 2.0, "should not detect skew")
  }

  // ==================== Integration Testing ====================

  test("should be able to extract QueryPlan information from a simple query") {
    val sparkSession = spark
    import sparkSession.implicits._

    // Create test data.
    val df = Seq((1, "Alice"), (2, "Bob"), (3, "Charlie")).toDF("id", "name")
    df.createOrReplaceTempView("test_table")

    // Execute query
    val result = spark.sql("SELECT * FROM test_table WHERE id > 1")
    result.collect()

    // Obtain QueryExecution.
    val qe = result.queryExecution

    // Validate that the plan exists
    assert(qe.logical != null)
    assert(qe.optimizedPlan != null)
    assert(qe.sparkPlan != null)
    assert(qe.executedPlan != null)

    // Validate that the plan string is not null
    assert(qe.logical.toString.nonEmpty)
    assert(qe.optimizedPlan.toString.nonEmpty)
    assert(qe.sparkPlan.toString.nonEmpty)
    assert(qe.executedPlan.toString.nonEmpty)
  }

  test("should be able to extract plan information from a Join query") {
    val sparkSession = spark
    import sparkSession.implicits._

    // Create test data.
    val df1 = Seq((1, "Alice"), (2, "Bob")).toDF("id", "name")
    val df2 = Seq((1, 100), (2, 200)).toDF("id", "score")

    df1.createOrReplaceTempView("users")
    df2.createOrReplaceTempView("scores")

    // execution Join query
    val result = spark.sql("SELECT u.name, s.score FROM users u JOIN scores s ON u.id = s.id")
    result.collect()

    // Obtain QueryExecution.
    val qe = result.queryExecution

    // Validate the plan contains a Join node.
    val planStr = qe.sparkPlan.toString
    assert(planStr.contains("Join") || planStr.contains("BroadcastHashJoin") || planStr.contains("SortMergeJoin"))
  }

  test("It should be able to extract plan information from an aggregate query") {
    val sparkSession = spark
    import sparkSession.implicits._

    // Create test data.
    val df = Seq((1, "A", 100), (2, "A", 200), (3, "B", 150)).toDF("id", "category", "value")
    df.createOrReplaceTempView("data")

    // Execute aggregation query
    val result = spark.sql("SELECT category, SUM(value) as total FROM data GROUP BY category")
    result.collect()

    // Obtain QueryExecution.
    val qe = result.queryExecution

    // Validate that the plan includes aggregation nodes
    val planStr = qe.sparkPlan.toString
    assert(planStr.contains("Aggregate") || planStr.contains("HashAggregate"))
  }
}
