package com.pista.spark.sql.connector.doris.batch

import com.pista.spark.sql.connector.BatchWriteResult
import org.apache.spark.internal.Logging
import org.apache.spark.sql.{DataFrame, SaveMode}

/**
 * Spark Doris Connector Write Mode
 *
 * Write into DataFrame using DataFrame.write.format("doris"), encapsulating the Stream Load protocol internally by Connector.
 * In parallel HTTP requests are initiated on the Executor, bypassing the Driver.
 *
 * Support Arrow format (serialization efficiency about 10x CSV) and 2PC Exactly-Once transactions.
 *
 * Design Explanation:
 * - not calling until write operation sourceDf.count()(TB full table Spark job is triggered once more for batch data. Spark Job)
 * - doris.write.fields Set only when columns are not empty to avoid Connector exceptions caused by empty strings
 * - None to register DorisDialect:Doris compatible MySQL protocol, Spark dialect satisfies the requirement for the Doris protocol.Spark the dialect is satisfied
 * - WriteRowCount is retrieved by the caller through a JDBC query to Doris
 *
 * @param config       Batch write configuration
 * @param sourceDf     Source DataFrame (not cached, Connector mode writes once)
 * @param jobTimestamp A uniform job timestamp generated by the caller for naming temp partitions
 *
 */
class SparkDorisConnectorWriter(
  config:       DorisBatchConfig,
  sourceDf:     DataFrame,
  jobTimestamp: Long
) extends Logging {

  def write(): BatchWriteResult = {
    val targetTable = buildTargetTable()
    logDebug(s"[ConnectorWriter] Preparing connector options, " +
      s"format=${config.dataFormat}, 2pc=${config.enable2PC}, " +
      s"partitions=${config.outputPartitions}, batchSize=${config.batchSize}")

    var writer = sourceDf.repartition(config.outputPartitions).write
      .format("doris")
      .option("doris.fenodes",                config.fenodes)
      .option("doris.table.identifier",       targetTable)
      .option("doris.user",                   config.user)
      .option("doris.password",               config.password)
      .option("doris.sink.batch.size",        config.batchSize.toString)
      .option("doris.sink.auto-redirect",     config.autoRedirect.toString)
      .option("doris.sink.label.prefix",      config.labelPrefix)
      .option("doris.sink.enable-2pc",        config.enable2PC.toString)
      .option("doris.sink.properties.format", config.dataFormat)
      .mode(SaveMode.Append)

    if (config.benodes.nonEmpty)
      writer = writer.option("doris.benodes", config.benodes)
    // Partition overwrite write: specify the temp partition for writing, and the Connector routes using doris.sink.properties.partitions.
    if (config.isPartitionOverwrite && config.targetPartitions.nonEmpty) {
      val tempNames = config.targetPartitions.map(p => s"tmp_${p}_${jobTimestamp}").mkString(",")
      writer = writer.option("doris.sink.properties.temporary_partitions", tempNames)
    }

    writer.save()

    BatchWriteResult(index = 0, rowCount = -1L, success = true)
  }

  private def buildTargetTable(): String = s"${config.database}.${config.table}"
}
