status = error
name = PistaLog4j2Config

appenders = console

appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{5}: %m%n%ex

rootLogger.level = info
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = Console

logger.hive.name = org.apache.hadoop.hive.metastore
logger.hive.level = fatal

logger.jetty.name = org.sparkproject.jetty
logger.jetty.level = warn
logger.jetty2.name = org.sparkproject.jetty.util.component.AbstractLifeCycle
logger.jetty2.level = error

logger.hive_functionregistry.name = org.apache.hadoop.hive.ql.exec.FunctionRegistry
logger.hive_functionregistry.level = error

logger.parquet.name = org.apache.parquet.CorruptStatistics
logger.parquet.level = error
logger.parquet2.name = parquet.CorruptStatistics
logger.parquet2.level = error
